### ISSUE TITLE
Fix packaging process to be automatic

### ISSUE THREAD

**Issue by BentleyJOakes** [AToMPM/atompm#148]
The packaged version of AToMPM is crucial for usage on Windows. However, this is annoying to make manually, especially as my main machine is on Linux.

This task is to fix up the packaging process as a GitHub action whenever a tag/release is made.

[GitHub action file](https://github.com/AToMPM/atompm/blob/master/.github/workflows/package_portable.yml)

[Packaging script](https://github.com/AToMPM/atompm/blob/master/packaging/package.sh)

First, ensure that the packaging script runs on a local Linux machine. Then, fix up the GitHub action to pull in the correct dependencies and build the package.

The previous failures were about installing the correct version of Wine, which shouldn't be a problem with the Ubuntu 22.04 image.

**Comment by vasco-sousa** [comment]
Mostly done with commit 415fd1dc32b49d27885d9027ed028cf24506309d.
It is running for Windows server. User manual is missing because resource is not available.
Might need some cleanup to have a smaller footprint and make sure all files are in the right place.
Still needs to be finished for Ubuntu if we want to maintain both versions, for redundancy and other accessibilities.

**Comment by BentleyJOakes** [comment]
For now, let's say this is completed by https://github.com/AToMPM/atompm/pull/161
Thanks for your hard work Vasco!
