### ISSUE TITLE
Issue with executing command "python mt/main.py" on MacOS

### ISSUE THREAD

**Issue by clyderemp** [AToMPM/atompm#164]
<img width="621" alt="Screenshot 2023-02-22 at 4 55 46 PM" src="https://user-images.githubusercontent.com/69777888/220768650-e1ebd763-9739-4da9-aea6-e4908a40658f.png">

I previously had python 3 and downgraded Python 2.7 and still having issues when executing the command.

**Comment by BentleyJOakes** [comment]
Could you try re-downloading the AToMPM files please, and then re-trying the installation instructions?

I ask because the error about the `No module named 'symbol'` was fixed last June by commit https://github.com/AToMPM/atompm/commit/6dc143255e066ef73e820cda5bfdc88c37ad587c. Therefore you have an old version with outdated dependencies and without a few clarifications in the README.

**Comment by BentleyJOakes** [comment]
Could you please try editing the `mt/ptcal/pytcore/rules/lqsrule.py` file, and removing the `from symbol import try_stmt` line? It is not needed anyways.

**Comment by BentleyJOakes** [comment]
Great! Please let me know if there are any other issues.
