### ISSUE TITLE
Generic links

### ISSUE THREAD

**Issue by esyriani** [AToMPM/atompm#77]
I open two models along side on the same canvas. I load the GenericGraph formalism. Note that it does not display the pruple square in the toolbar, but the path to the metamodel file. It is not possible to instantiate a Generic node or generic edge. It is also not possible to connect to model elements from different metamodels.

**Comment by BentleyJOakes** [comment]
The Generic meta-model only contains the Generic edge, not the class. To create a generic edge, one loads the toolbar, then creates an edge between two elements.
* Issue #13 is about adding a Generic node concept.

The path to the metamodel file in the toolbar is because there are no class icons defined. An enhancement could be to print a warning message. However, the relevant code is proving difficult to find.
